---
# The name of the site--used to generate the /srv/{{ site_name }} directory.
site_name: richardsite

# Linux user/group things should run as
richard_user: richard
richard_group: richard

richard_dir: "/srv/{{ site_name }}"
richard_venv: "{{ richard_dir }}/venv"
richard_uwsgi_ini: "{{ richard_dir }}/richard.wsgi.ini"
richard_port: 8000
richard_source: "{{ richard_dir }}/richard"
richard_static: "{{ richard_source }}/src/richard/static"
richard_repo: "https://github.com/pyvideo/richard.git"
# What version of the repository to check out. This can be the full 40-character
# SHA-1 hash, the literal string HEAD, a branch name, or a tag name.
richard_version: master
DATABASE_URL: "postgres://:5432/richard"
DJANGO_DEBUG: False
DJANGO_CONFIGURATION: Dev
DJANGO_SECRET_KEY: "dummy"
RICHARD_API: True
RICHARD_SITE_URL: "http://127.0.0.1:8000"
DJANGO_SETTINGS_MODULE: "richard.config.settings"
richard_environment: { DATABASE_URL: "{{ DATABASE_URL }}", DJANGO_DEBUG: "{{ DJANGO_DEBUG }}", DJANGO_CONFIGURATION: "{{ DJANGO_CONFIGURATION }}", DJANGO_SECRET_KEY: "{{ DJANGO_SECRET_KEY }}", RICHARD_API: "{{ RICHARD_API }}", RICHARD_SITE_URL: "{{ RICHARD_SITE_URL }}" }
