# Playbook for creating a new rackspace cloud server.
#
# The authorized_keys file must be in ./file/authorized_keys
#
# ansible-playbook -i rax_inventory -vv rax_create.yml 
---
- name: Create a Rackspace Cloud Server
  hosts: localhost
  user: root
  connection: local
  gather_facts: False

  vars_files:
    - vars/all.yml

  tasks:
    - name: Provision an instance
      local_action:
          module: rax
          name: "{{ rax_name }}"
          flavor: "{{ rax_flavor }}"
          image: "{{ rax_image }}"
          files:
            /root/.ssh/authorized_keys: ./files/authorized_keys
          meta:
            provisioned_by: ansible
            used_for: pyvideo
          wait: yes
      register: rax

    - name: Add new instance to host group
      local_action: 
        module: add_host
        hostname: "{{ item.name}}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }}"
        groupname: raxhosts
      with_items: rax.success
      when: rax.action == 'create'

- name: Configure basics
  hosts: raxhosts
  user: root

  roles:
    - create
