---
- name: start richard
  service: name=richard.uwsgi state=started

- name: restart richard
  service: name=richard.uwsgi state=restarted

- name: restart nginx
  service: name=nginx state=restarted
