---
- name: richard user exists
  user: name="{{ richard_user }}" shell=/bin/bash state=present

- name: richard site directory tree exists
  file: path="{{ item }}" state=directory owner="{{ richard_user }}" group="{{ richard_group }}"
  with_items:
    - "{{ richard_dir }}"
    - "{{ richard_dir }}/logs"

- name: richard is cloned
  git: repo="{{ richard_repo }}"
       dest="{{ richard_source }}"
       version="{{ richard_version }}"
  sudo_user: "{{ richard_user }}"

- name: install richard dependencies
  pip: name=".\[dev,postgresql\]"
       chdir="{{ richard_source }}"
       extra_args="-e"

- name: install uwsgi
  pip: name=uwsgi
       version=2.0.9

- name: richard syncdb
  django_manage: >
    command="syncdb --noinput --migrate"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard migrate
  django_manage: >
    command=migrate
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard collectstatic
  django_manage: >
    command="collectstatic --noinput"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard uwsgi.ini
  template: >
    src=richard.uwsgi.ini.j2
    dest="{{ richard_uwsgi_ini }}"
    owner=root
    group=root
    mode=644

- name: richard supervisor.conf
  template: >
    src=richard.supervisor.conf.j2
    dest=/etc/supervisor/conf.d/richard.conf
    owner=root
    group=root
    mode=600
  notify: start richard
