---
- name: richard site directory tree exists
  file: path="{{ item }}" state=directory owner="{{ richard_user }}" group="{{ richard_group }}"
  with_items:
    - "{{ richard_dir }}"
    - "{{ richard_dir }}/logs"

- name: richard is cloned
  git: repo="{{ richard_repo }}"
       dest="{{ richard_source }}"
       version="{{ richard_version }}"
  sudo_user: "{{ richard_user }}"

- name: richard clone belongs to richard user
  file: path="{{ richard_source }}"
        recurse=yes
        owner="{{ richard_user }}"

- name: richard dependencies are installed
  pip: name=".\[dev,postgresql\]"
       chdir="{{ richard_source }}"
       extra_args="-e"

- name: uwsgi is installed
  pip: name=uwsgi
       version=2.0.9

- name: richard database is synced with models
  django_manage: >
    command="syncdb --noinput --migrate"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard database is up to date with migrations
  django_manage: >
    command=migrate
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard static files are up to date via collectstatic
  django_manage: >
    command="collectstatic --noinput"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard uwsgi.ini is configured
  template: >
    src=richard.uwsgi.ini.j2
    dest="{{ richard_uwsgi_ini }}"
    owner=root
    group=root
    mode=644

- name: richard supervisor.conf is configured
  template: >
    src=richard.supervisor.conf.j2
    dest=/etc/supervisor/conf.d/richard.conf
    owner=root
    group=root
    mode=600
  notify: start richard
