---
- name: richard site directory tree exists
  file: path="{{ item }}" state=directory owner="{{ richard_user }}" group="{{ richard_group }}"
  with_items:
    - "{{ richard_dir }}"
    - "{{ richard_dir }}/logs"

- name: richard is cloned
  git: repo="{{ richard_repo }}"
       dest="{{ richard_source }}"
       version="{{ richard_version }}"
  sudo_user: "{{ richard_user }}"

- name: richard clone belongs to richard user
  file: path="{{ richard_source }}"
        recurse=yes
        owner="{{ richard_user }}"

- name: richard dependencies are installed
  pip: name=".\[dev,postgresql\]"
       chdir="{{ richard_source }}"
       extra_args="-e"

- name: richard database is synced with models
  django_manage: >
    command="syncdb --noinput --migrate"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard database is up to date with migrations
  django_manage: >
    command=migrate
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard static files are up to date via collectstatic
  django_manage: >
    command="collectstatic --noinput"
    app_path="{{ richard_source }}"
    settings=richard.config.settings
  sudo_user: "{{ richard_user }}"
  environment: "{{ richard_env }}"

- name: richard uwsgi.ini is available
  template: >
    src=richard.uwsgi.ini.j2
    dest="{{ richard_uwsgi_ini }}"
    owner=root
    group=root
    mode=644

- name: upstart job is configured
  template: >
    src=richard.uwsgi.conf.j2
    dest=/etc/init/richard.uwsgi.conf
  notify:
    - restart richard

- name: richard nginx site is available
  template: >
    src=richard_web.conf.j2
    dest=/etc/nginx/sites-available/richard_web.conf

- name: default nginx site is disabled
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: richard nginx site is enabled
  file:
    src=/etc/nginx/sites-available/richard_web.conf
    dest=/etc/nginx/sites-enabled/richard_web.conf
    state=link
  notify:
    - restart nginx

