# Playbook for creating a new rackspace cloud server.
#
# The authorized_keys file must be in ./file/authorized_keys
#
# ansible-playbook -i rax_inventory -vv rax_create.yml 
---
- name: Create a Rackspace Cloud Server
  hosts: localhost
  user: root
  connection: local
  gather_facts: False

  tasks:
    - name: Provision an instance
      local_action:
          module: rax
          name: ansible_pyvideo
          # 3 is standard 1 gig instance
          flavor: 3
          # this image is Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
          image: 598a4282-f14b-4e50-af4c-b3e52749d9f9
          files:
            /root/.ssh/authorized_keys: ./files/authorized_keys
          meta:
            provisioned_by: ansible
            used_for: pyvideo
          wait: yes
      register: rax
