---
- name: required packages are installed
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - python-software-properties
    - build-essential
    - python-dev
    - python-pip
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libxslt1-dev
    - git
    # not required, but nice to have
    - tig
    - vim
    - curl
    - tmux
    - htop
    - ack-grep

- name: install pip from pypi
  pip: name=pip extra_args="--upgrade"
  tags: pip

- name: install virtualenv
  pip: name=virtualenv
  tags: pip
