---
- name: required packages are installed
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - python-software-properties
    - build-essential
    - python-dev
    - python-pip
    - postgresql
    - postgresql-server-dev-9.3
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libxslt1-dev
    - git
    - supervisor
    # not required, but nice to have
    - tig
    - vim
    - curl
    - tmux
    - htop
    - ack-grep

- name: pip is upgraded from pypi
  pip: name=pip extra_args="--upgrade"
  tags: pip

- name: virtualenv is installed from pypi
  pip: name=virtualenv extra_args="--upgrade"
  tags: pip

- name: richard user exists
  user: name="{{ richard_user }}" shell=/bin/bash state=present

